config/routes.rb
Rails.application.routes.draw do
  root 'scripts#index'
  resources :scripts do
    collection do
      get :hot
      get :popular
    end
    resources :sentences do
    end
  end

end

app/models/script.rb
class Script < ActiveRecord::Base
  has_many :sentences
  accepts_nested_attributes_for :sentences, allow_destroy: true
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :script
  enum actor: [:whole, :boke, :tsukkomi]
  enum action: [:message, :bokeru, :tsukkomu]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show]

  def index
    scripts = Script.order('created_at desc').take(10)
    @top = scripts.first
    @scripts = scripts.reject do |script|
      script == @top
    end
  end

  def show
  end

  def new
    @script = Script.new
  end

  def hot
    # TODO take hot scripts
    @top = Script.first
    @scripts = Script.take(10)
    render "index"
  end

  def popular
    # TODO take popular scripts
    @top = Script.first
    @scripts = Script.take(10)
    render "index"
  end

  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render action: 'show', status: :created, location: @script }
      else
        format.html { render action: 'new' }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_script
    @script = Script.find(params[:id])
  end

  def script_params
    params.require(:script).permit(:title, sentences_attributes: [:id, :actor, :action, :message, :script_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
  def icon_class(target)
    case target
    when "whole"
      return "fa fa-users"
    when "boke"
      return "fa fa-male"
    when "tsukkomi"
      return "fa fa-female"
    when "message"
      return "fa fa-commenting"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <title>Manzai</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <i class="fa fa-home">Manzai</i>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">新規登録</a></li>
          <li><a href="#">ログイン</a></li>
          <li><%= link_to '台本作成', new_script_path %></li>
          <li><a href="#">ヘルプ</a></li>
        </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <%= yield %>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
</body>
<%= yield :body_end %>
</html>

app/views/scripts/_form.html.erb
<%= nested_form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @script.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="">
    <%= f.fields_for :sentences do |sentence| %>
      <%= render "sentence_fields", f: sentence %>
    <% end %>
    <%= f.link_to_add "Add Sentence", :sentences %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/_panel.html.erb
<div class="panel panel-default text-center">
	<div class="panel-heading">
		<%= script.title %>
	</div>
	<div class="panel-body">
		<%= link_to script_path(script) do %>
      <i class="fa fa-play-circle fa-5x"></i>
    <% end %>
	</div>
	<!--
	<div class="panel-footer">
		パネルのフッター
	</div>
	-->
</div>

app/views/scripts/_sentence_fields.html.erb
<div class="field">
  <%= f.hidden_field :id %>
</div>
<div class="field">
  <%= f.label :message %><br>
  <%= f.text_field :message %>
</div>
<%= f.link_to_remove 'Remove Event' %>

app/views/scripts/index.html.erb
<div class="row center-block">
  <%= render 'panel', script: @top %>
</div>
<% @scripts.each do |script| %>
  <div class="row center-block">
    <%= render 'panel', script: script %>
  </div>
<% end %>

app/views/scripts/new.html.erb
<%= render 'form' %>

<%= link_to '戻る', scripts_path %>

app/views/scripts/show.html.erb
<div id="enchant-stage" class="center-block" data-script-id="<%= @script.id %>"></div>
<%= link_to '戻る', scripts_path %>

<% content_for :body_end do %>
　<%= javascript_include_tag "scripts" %>
<% end %>